CREATE TABLE IF NOT EXISTS devices (
	"id"	INTEGER NOT NULL UNIQUE,
	"name"	TEXT NOT NULL DEFAULT 'captor',
	"type"	TEXT NOT NULL DEFAULT 'infrared',
	"sensity"	INTEGER NOT NULL DEFAULT 1,
	PRIMARY KEY("id" AUTOINCREMENT)
);